export {
  authenticatedUserSchema,
  loginInputSchema,
  roleSchema,
  sessionResponseSchema,
} from "./auth.js";
export type { AuthenticatedUser, LoginInput, Role, SessionResponse } from "./auth.js";
export {
  ADMIN_MANAGEMENT_RULES,
  adminBookIdParamsSchema,
  adminBookInputSchema,
  adminBookResponseSchema,
  adminBookSchema,
  adminBooksResponseSchema,
  adminCreateBookInputSchema,
  adminCreateGenreInputSchema,
  adminErrorResponseSchema,
  adminGenreIdParamsSchema,
  adminGenreInputSchema,
  adminGenreResponseSchema,
  adminGenreSchema,
  adminGenresResponseSchema,
  adminIsbnSchema,
  adminManagementRulesSchema,
  adminRecordStatusSchema,
  adminStatusQuerySchema,
  adminUpdateBookInputSchema,
  adminUpdateGenreInputSchema,
} from "./admin.js";
export type {
  AdminBook,
  AdminBookIdParams,
  AdminBookInput,
  AdminBookResponse,
  AdminBooksResponse,
  AdminCreateBookInput,
  AdminCreateGenreInput,
  AdminErrorResponse,
  AdminGenre,
  AdminGenreIdParams,
  AdminGenreInput,
  AdminGenreResponse,
  AdminGenresResponse,
  AdminManagementRules,
  AdminRecordStatus,
  AdminStatusQuery,
  AdminUpdateBookInput,
  AdminUpdateGenreInput,
} from "./admin.js";
export {
  bookIdParamsSchema,
  catalogueArchiveVisibilitySchema,
  catalogueBookDetailResponseSchema,
  catalogueBookDetailSchema,
  catalogueBookNotFoundErrorResponseSchema,
  catalogueBooksQuerySchema,
  catalogueBooksResponseSchema,
  catalogueBookSummarySchema,
  catalogueErrorResponseSchema,
  catalogueInvalidBookIdErrorResponseSchema,
  catalogueInvalidQueryErrorResponseSchema,
  cataloguePaginationMetaSchema,
  catalogueSortSchema,
  catalogueUnauthenticatedErrorResponseSchema,
  CATALOGUE_ARCHIVE_VISIBILITY,
  CATALOGUE_DEFAULT_PAGE,
  CATALOGUE_DEFAULT_PAGE_SIZE,
  CATALOGUE_MAX_PAGE,
  CATALOGUE_MAX_PAGE_SIZE,
  genreSlugSchema,
  genreSummarySchema,
  genresResponseSchema,
} from "./catalogue.js";
export type {
  BookIdParams,
  CatalogueArchiveVisibility,
  CatalogueBookDetail,
  CatalogueBookDetailResponse,
  CatalogueBooksQuery,
  CatalogueBooksResponse,
  CatalogueBookSummary,
  CatalogueErrorResponse,
  CataloguePaginationMeta,
  CatalogueSort,
  GenresResponse,
  GenreSummary,
} from "./catalogue.js";
export {
  discoveryResponseSchema,
  PUBLIC_DISCOVERY_LIMIT,
  publicBookPreviewSchema,
} from "./discovery.js";
export type { DiscoveryResponse, PublicBookPreview } from "./discovery.js";
export {
  availableReadingListBookSchema,
  engagementArchiveVisibilitySchema,
  engagementErrorResponseSchema,
  ENGAGEMENT_ARCHIVE_VISIBILITY,
  favouriteGenreIdsInputSchema,
  favouriteGenresInvalidInputErrorResponseSchema,
  favouriteGenresResponseSchema,
  FOR_YOUR_SHELVES_LIMIT,
  forYourShelvesResponseSchema,
  MAX_FAVOURITE_GENRES,
  readingListBookIdParamsSchema,
  readingListBookSchema,
  readingListEntryResponseSchema,
  readingListEntrySchema,
  readingListInvalidInputErrorResponseSchema,
  readingListResponseSchema,
  readingListStatusSchema,
  readingListUpdateInputSchema,
  unavailableReadingListBookSchema,
} from "./engagement.js";
export type {
  AvailableReadingListBook,
  EngagementArchiveVisibility,
  EngagementErrorResponse,
  FavouriteGenreIdsInput,
  FavouriteGenresResponse,
  ForYourShelvesResponse,
  ReadingListBook,
  ReadingListEntry,
  ReadingListEntryResponse,
  ReadingListResponse,
  ReadingListStatus,
  ReadingListUpdateInput,
  UnavailableReadingListBook,
} from "./engagement.js";
export { apiErrorCodeSchema, apiErrorResponseSchema } from "./errors.js";
export type { ApiErrorCode, ApiErrorResponse } from "./errors.js";
export { healthResponseSchema } from "./health.js";
export type { HealthResponse } from "./health.js";
